### ISSUE TITLE
Config to use easily and fast

### ISSUE THREAD

**Issue by attakei** [attakei/sphinxcontrib-googlefonts#3]
Configuration to apply globally in document.

## example

`conf.py`:

```python
google_fonts_maps = {
  "body": ("Noto Sans JP", "serif"),
  "h1, h2": "M PLUS 1p",
}
```

`document`:

```css
body {
   font-family: "Noto Sans JP", serif;
}
h1, h2 {
  font-family: "M PLUS 1p";
}
```
